# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mpg.proto',
  package='mpg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tmpg.proto\x12\x03mpg\"\x1c\n\nSendMyMove\x12\x0e\n\x06myMove\x18\x01 \x01(\t\"(\n\x10SendOpponentMove\x12\x14\n\x0copponentMove\x18\x01 \x01(\t2A\n\tTicTacToe\x12\x34\n\x08PlayTurn\x12\x0f.mpg.SendMyMove\x1a\x15.mpg.SendOpponentMove\"\x00\x62\x06proto3'
)




_SENDMYMOVE = _descriptor.Descriptor(
  name='SendMyMove',
  full_name='mpg.SendMyMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='myMove', full_name='mpg.SendMyMove.myMove', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=46,
)


_SENDOPPONENTMOVE = _descriptor.Descriptor(
  name='SendOpponentMove',
  full_name='mpg.SendOpponentMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opponentMove', full_name='mpg.SendOpponentMove.opponentMove', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['SendMyMove'] = _SENDMYMOVE
DESCRIPTOR.message_types_by_name['SendOpponentMove'] = _SENDOPPONENTMOVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMyMove = _reflection.GeneratedProtocolMessageType('SendMyMove', (_message.Message,), {
  'DESCRIPTOR' : _SENDMYMOVE,
  '__module__' : 'mpg_pb2'
  # @@protoc_insertion_point(class_scope:mpg.SendMyMove)
  })
_sym_db.RegisterMessage(SendMyMove)

SendOpponentMove = _reflection.GeneratedProtocolMessageType('SendOpponentMove', (_message.Message,), {
  'DESCRIPTOR' : _SENDOPPONENTMOVE,
  '__module__' : 'mpg_pb2'
  # @@protoc_insertion_point(class_scope:mpg.SendOpponentMove)
  })
_sym_db.RegisterMessage(SendOpponentMove)



_TICTACTOE = _descriptor.ServiceDescriptor(
  name='TicTacToe',
  full_name='mpg.TicTacToe',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlayTurn',
    full_name='mpg.TicTacToe.PlayTurn',
    index=0,
    containing_service=None,
    input_type=_SENDMYMOVE,
    output_type=_SENDOPPONENTMOVE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TICTACTOE)

DESCRIPTOR.services_by_name['TicTacToe'] = _TICTACTOE

# @@protoc_insertion_point(module_scope)
