# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mpg.proto',
  package='mpg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tmpg.proto\x12\x03mpg\"\x19\n\nPlayerMove\x12\x0b\n\x03pos\x18\x01 \x01(\t\"\x1b\n\x0c\x43urrentBoard\x12\x0b\n\x03pos\x18\x01 \x01(\t2=\n\tTicTacToe\x12\x30\n\x08PlayTurn\x12\x0f.mpg.PlayerMove\x1a\x11.mpg.CurrentBoard\"\x00\x62\x06proto3'
)




_PLAYERMOVE = _descriptor.Descriptor(
  name='PlayerMove',
  full_name='mpg.PlayerMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='mpg.PlayerMove.pos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)


_CURRENTBOARD = _descriptor.Descriptor(
  name='CurrentBoard',
  full_name='mpg.CurrentBoard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='mpg.CurrentBoard.pos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['PlayerMove'] = _PLAYERMOVE
DESCRIPTOR.message_types_by_name['CurrentBoard'] = _CURRENTBOARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerMove = _reflection.GeneratedProtocolMessageType('PlayerMove', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERMOVE,
  '__module__' : 'mpg_pb2'
  # @@protoc_insertion_point(class_scope:mpg.PlayerMove)
  })
_sym_db.RegisterMessage(PlayerMove)

CurrentBoard = _reflection.GeneratedProtocolMessageType('CurrentBoard', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTBOARD,
  '__module__' : 'mpg_pb2'
  # @@protoc_insertion_point(class_scope:mpg.CurrentBoard)
  })
_sym_db.RegisterMessage(CurrentBoard)



_TICTACTOE = _descriptor.ServiceDescriptor(
  name='TicTacToe',
  full_name='mpg.TicTacToe',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlayTurn',
    full_name='mpg.TicTacToe.PlayTurn',
    index=0,
    containing_service=None,
    input_type=_PLAYERMOVE,
    output_type=_CURRENTBOARD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TICTACTOE)

DESCRIPTOR.services_by_name['TicTacToe'] = _TICTACTOE

# @@protoc_insertion_point(module_scope)
